### ISSUE TITLE
weight question

### ISSUE THREAD

**Issue by PlutoQyl** [TencentARC/BrushNet#1]
### Describe the bug

**I downloaded the weights you guys provided, but there seems to be some issues with the weights**

ValueError: Cannot load <class 'diffusers.models.brushnet.BrushNetModel'> from /model/BrushNet/unet because the following keys are missing: 
 brushnet_up_blocks.11.weight, brushnet_up_blocks.4.bias, brushnet_up_blocks.10.bias, brushnet_down_blocks.9.bias, brushnet_up_blocks.6.weight, brushnet_down_blocks.3.bias, brushnet_down_blocks.5.bias, brushnet_up_blocks.7.bias, brushnet_up_blocks.3.bias, brushnet_up_blocks.12.weight, brushnet_down_blocks.8.weight, brushnet_up_blocks.13.weight, brushnet_down_blocks.6.bias, brushnet_up_blocks.9.bias, brushnet_down_blocks.11.bias, brushnet_down_blocks.5.weight, brushnet_down_blocks.4.bias, brushnet_mid_block.bias, brushnet_down_blocks.2.weight, brushnet_down_blocks.3.weight, brushnet_down_blocks.1.bias, brushnet_down_blocks.7.bias, brushnet_down_blocks.0.bias, brushnet_up_blocks.12.bias, brushnet_up_blocks.7.weight, brushnet_up_blocks.8.bias, brushnet_up_blocks.2.bias, brushnet_up_blocks.14.weight, brushnet_up_blocks.0.weight, brushnet_up_blocks.11.bias, brushnet_up_blocks.3.weight, brushnet_up_blocks.1.bias, brushnet_up_blocks.6.bias, brushnet_up_blocks.4.weight, brushnet_down_blocks.4.weight, brushnet_up_blocks.0.bias, brushnet_down_blocks.0.weight, brushnet_up_blocks.2.weight, brushnet_up_blocks.10.weight, brushnet_mid_block.weight, brushnet_up_blocks.13.bias, brushnet_up_blocks.1.weight, brushnet_up_blocks.14.bias, brushnet_down_blocks.7.weight, brushnet_up_blocks.8.weight, brushnet_up_blocks.9.weight, brushnet_down_blocks.1.weight, brushnet_down_blocks.10.weight, conv_in_condition.bias, brushnet_down_blocks.8.bias, conv_in_condition.weight, brushnet_up_blocks.5.bias, brushnet_down_blocks.2.bias, brushnet_down_blocks.6.weight, brushnet_down_blocks.11.weight, brushnet_down_blocks.10.bias, brushnet_down_blocks.9.weight, brushnet_up_blocks.5.weight. 
 Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct.

### Reproduction

realisticVisionV60B1_v51VAE

### System Info

- `diffusers` version: 0.27.0
- Platform: Linux-5.4.143.bsk.8-amd64-x86_64-with-glibc2.17
- Python version: 3.8.18
- PyTorch version (GPU?): 1.12.1+cu116 (True)
- Huggingface_hub version: 0.21.4
- Transformers version: 4.38.2
- Accelerate version: 0.20.3
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by Arcxml** [comment]
hello, I want to ask if you have get the ckpt by yourself ? I met some problems

**Comment by Arcxml** [comment]
@PlutoQyl

**Comment by juxuan27** [comment]
Hi, @Arcxml and @PlutoQyl ! We have released the checkpoint and revised the inference code. Please check if there is any problem~

**Comment by Arcxml** [comment]
Okay ，thank you



---- Replied Message ----
| From | Xuan ***@***.***> |
| Date | 03/28/2024 14:03 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [TencentARC/BrushNet] weight question (Issue #1) |

Hi, @Arcxml and @PlutoQyl ! We have released the checkpoint and revised the inference code. Please check if there is any problem~

**Comment by PlutoQyl** [comment]
> Hi, @Arcxml and @PlutoQyl ! We have released the checkpoint and revised the inference code. Please check if there is any problem~

thank you
