### ISSUE TITLE
The object added has a strange shape

### ISSUE THREAD

**Issue by AGI0102** [TencentARC/BrushNet#11]
![rabbit](https://github.com/TencentARC/BrushNet/assets/155818896/c8781b79-4a3b-42c6-8e6b-c2c065d2314f)
![bird](https://github.com/TencentARC/BrushNet/assets/155818896/4824a291-1b13-40b3-b011-d65a182bcfb4)
When I tried the huggingface demo, I found that the shape of the object was always very close to the shape of the mask, and it was very strange, why

**Comment by juxuan27** [comment]
Hi, @AGI0102 ! Thank you for your focus. As mentioned in [this issue](https://github.com/TencentARC/BrushNet/issues/10), we use a segmentation mask-based ckpt in our hugging face demo. Thus the generated object shape should be totally aligned with that you given, this would be especially used in some cases such as product exhibition. To generate an object with a shape that is not the same as the mask, please use random mask-based ckpt provided in the Google Drive link. You may read the readme and paper for more information.
