### ISSUE TITLE
It is recommended to upload the ckpt to HuggingFace, as there are always download failures with Google Drive.

### ISSUE THREAD

**Issue by ggsddu7** [TencentARC/BrushNet#12]
It is recommended to upload the ckpt to Hugging Face, as there are always download failures with Google Drive.

**Comment by juxuan27** [comment]
Hi, @ggsddu7 ! Thank you for your focus. Do you mean the ckpt provided like this: https://huggingface.co/spaces/TencentARC/BrushNet/tree/main ? What kind of format would be convenient for you to download? I can upload them to huggingface if you need other formats.

**Comment by juxuan27** [comment]
Hi, @marks202309 . It might be difficult for us to upload the dataset on hugging face due to license issue. Sorry for the inconvenience.

**Comment by juxuan27** [comment]
Already uploaded
