### ISSUE TITLE
using with ip adapter

### ISSUE THREAD

**Issue by SlZeroth** [TencentARC/BrushNet#14]
can I using brushnet with ip adapter ?

**Comment by juxuan27** [comment]
I think it can since it is possible to combine controlnet with brushnet. I will try that later

**Comment by juxuan27** [comment]
Hi! It has already supported by @kijai at [here](https://github.com/kijai/ComfyUI-BrushNet-Wrapper). Thanks for his effort and hope you enjoy it!
