### ISSUE TITLE
Can you provide the code for data preprocessing?

### ISSUE THREAD

**Issue by Chevolier** [TencentARC/BrushNet#16]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

I noticed you preprocessed the images and generated several features for each image, could you provide the preprocessing codes? Thanks a lot!

**Describe the solution you'd like.**

**Describe alternatives you've considered.**

**Additional context.**

**Comment by juxuan27** [comment]
Hi, @Chevolier ! I directly use [Grounded-SAM](https://github.com/IDEA-Research/Grounded-Segment-Anything) to process the images. Using either RAM or Tag2Text is fine. You may refer to their repo for the details.

**Comment by Chevolier** [comment]
> Hi, @Chevolier ! I directly use [Grounded-SAM](https://github.com/IDEA-Research/Grounded-Segment-Anything) to process the images. Using either RAM or Tag2Text is fine. You may refer to their repo for the details.

Got it, thanks a lot!
