### ISSUE TITLE
when to release checkpoint (sdv1.5)?

### ISSUE THREAD

**Issue by Arcxml** [TencentARC/BrushNet#2]
### Model/Pipeline/Scheduler description

hello! Thanks for your excellent work. I want to ask when to release the checkpoint? Thanks a lot :-)

### Open source status

- [x] The model implementation is available.
- [x] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by juxuan27** [comment]
Hi, @Arcxml ! We have updated our code and readme. Please check the latest version!
