### ISSUE TITLE
Compare with the 9-channel controlnet-inpainting model

### ISSUE THREAD

**Issue by YoucanBaby** [TencentARC/BrushNet#21]
Dear developer,

Thank you for your wonderful work. 

![image](https://github.com/TencentARC/BrushNet/assets/43912540/6f5b6638-fc99-4793-a64e-584904007112)

The paper seems to only compare 4-channel controlnet-inpainting.
Have you ever compared the 9-channel controlnet-inpainting model?
What I mean is that the input of UNet is 9-channel.

Best wishes.

**Comment by juxuan27** [comment]
Hi, @YoucanBaby ! Could you please give me a link to the 9-channel ControlNet? In the comparison in my paper, I simply use the default setting of ControlNet, which is 4-channel. Moreover, our ablation has shown results of a model design similar to 9-channel ControlNet.
