### ISSUE TITLE
Often get all zero image when inpainting mask is small

### ISSUE THREAD

**Issue by ypflll** [TencentARC/BrushNet#24]
Thank you for opening source this work and the result is wonderful!
But I met met a problem when I tried to edit cartoon images:

- Checkpoint: AnythingV5_Ink.
- Brushnet model: random.
- Prompt: 1girl, 1boy with mouth open (or closed)
- Image and mask:

<img width="386" alt="image" src="https://github.com/TencentARC/BrushNet/assets/12528364/3b8f0f10-603f-4bfe-9b9a-e0c67fd707de">

I often get a result that is all zeros:
<img width="223" alt="image" src="https://github.com/TencentARC/BrushNet/assets/12528364/6d262ad3-5a4a-4785-a14e-94537b9625f1">

Adjusting prompt seems no use.
When I change to another checkpoint, like dreamshaper_v8, the result is reasonable(But not cartoon style I want).

So, why for AnythingV5_Ink, the results are often all zeros. Seems that the model is collapsed.
Do you guys have any idea on how to avoid this?

**Comment by juxuan27** [comment]
Hi, have you check whether you close the nsfw checker?

**Comment by ypflll** [comment]
Thanks for your reply.

I checked the code, and it seems that `safety_checker ` is None.
I used ComfyUI, which uses `StableDiffusionBrushNetPipeline  ` from diffusers. 

https://civitai.com/api/download/models/108289?type=Model&format=SafeTensor&size=pruned&fp=fp32

**Comment by juxuan27** [comment]
Can you try changing a VAE? I also encountered this problem in training SDXL, and changing the VAE encoder works for me. I don't know whether it would also happen in sdv1.5.

**Comment by ypflll** [comment]
Thanks for your advice. I'll try it.
