### ISSUE TITLE
BrushNet with other ControlNet models.

### ISSUE THREAD

**Issue by Shuvo001** [TencentARC/BrushNet#26]
Thanks for your great work!
But i wanted to make sure about one thing.
**Is it possible to use BurshNet inpainting model with other ControlNet models such as Canny, Segmentation etc to get the better outputs or other purposes?**

**Comment by MingZeY** [comment]
same ask

**Comment by juxuan27** [comment]
Yeah I think someone had tried that and found it works. As shown [here](https://github.com/TencentARC/BrushNet/issues/8).

**Comment by juxuan27** [comment]
The node in comfyui has supported this. Issue closed.
