### ISSUE TITLE
Create Custom BrushData set.

### ISSUE THREAD

**Issue by Shuvo001** [TencentARC/BrushNet#29]
Thanks for your novel work!
**I would like to fine-tune your model on my custom dataset.** But in this repo there have no detail information about how to create my own BurshData set.
I have downloaded few files from  [](https://huggingface.co/datasets/random123123/BrushData) and when i have extracted i have seen something like this:
![brushdata](https://github.com/TencentARC/BrushNet/assets/61898803/ddcba30f-97bc-415a-9931-61eb8723e3e1)

So i am quite confused how can i convert my (image,masks,caption) to this format!
I will really appreciate if you give me some informations about it, Thanks!!

**Comment by juxuan27** [comment]
Hi, we use webdataset to store the data. You may refer to [this](https://webdataset.github.io/webdataset/creating/).

**Comment by zhangyonle** [comment]
> Thanks for your novel work! **I would like to fine-tune your model on my custom dataset.** But in this repo there have no detail information about how to create my own BurshData set. I have downloaded few files from and when i have extracted i have seen something like this: ![brushdata](https://private-user-images.githubusercontent.com/61898803/329559334-ddcba30f-97bc-415a-9931-61eb8723e3e1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjYxNTgsIm5iZiI6MTcyNjIyNTg1OCwicGF0aCI6Ii82MTg5ODgwMy8zMjk1NTkzMzQtZGRjYmEzMGYtOTdiYy00MTVhLTk5MzEtNjFlYjg3MjNlM2UxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDExMTA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZTBjZDcwYzQwNTMxMThlNDA3YzIyYWIyZDk2Zjg5NWNhZWIyNjY4Y2NjZDk4N2NlM2RiZDIzNDQ1M2ZlN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kqhE-XkHD93UVrofuj4ACgBnwGaIuD4PHBwFGie19R4)
> 
> So i am quite confused how can i convert my (image,masks,caption) to this format! I will really appreciate if you give me some informations about it, Thanks!!

Hello, I have original image (.png), corrseponding mask image (.png),  and 5 captions every image, How can I convert them to these format as shown in this picture like xx.aesthetic_score, xx.caption, xx.height, xx.image, xx.original_key, xx.segmentation, xx.url, xx.width,

**Comment by jayhxmo** [comment]
+1 on @zhangyonle's question.

**Comment by huangjie-nlp** [comment]
> > 感谢您的创新工作！**我想在我的自定义数据集上微调您的模型。**但是这个仓库里没有关于如何创建我自己的 BurshData 数据集的详细信息。我从那里下载了几个文件，解压后我看到了类似这样的内容：![brushdata](https://private-user-images.githubusercontent.com/61898803/329559334-ddcba30f-97bc-415a-9931-61eb8723e3e1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjYxNTgsIm5iZiI6MTcyNjIyNTg1OCwicGF0aCI6Ii82MTg5ODgwMy8zMjk1NTkzMzQtZGRjYmEzMGYtOTdiYy00MTVhLTk5MzEtNjFlYjg3MjNlM2UxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDExMTA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZTBjZDcwYzQwNTMxMThlNDA3YzIyYWIyZDk2Zjg5NWNhZWIyNjY4Y2NjZDk4N2NlM2RiZDIzNDQ1M2ZlN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kqhE-XkHD93UVrofuj4ACgBnwGaIuD4PHBwFGie19R4)
> > 所以我很困惑，如何将我的（图像、蒙版、标题）转换成这种格式！如果您能提供一些相关信息，我将不胜感激，谢谢！
> 
> 您好，我有原始图像（.png）、相应的蒙版图像（.png）和每张图片的 5 个标题，我怎样才能将它们转换为此图片所示的格式，例如 xx.aesthetic_score、xx.caption、xx.height、xx.image、xx.original_key、xx.segmentation、xx.url、xx.width，

Is this problem solved?

**Comment by huangjie-nlp** [comment]
> > Thanks for your novel work! **I would like to fine-tune your model on my custom dataset.** But in this repo there have no detail information about how to create my own BurshData set. I have downloaded few files from and when i have extracted i have seen something like this: ![brushdata](https://private-user-images.githubusercontent.com/61898803/329559334-ddcba30f-97bc-415a-9931-61eb8723e3e1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjYxNTgsIm5iZiI6MTcyNjIyNTg1OCwicGF0aCI6Ii82MTg5ODgwMy8zMjk1NTkzMzQtZGRjYmEzMGYtOTdiYy00MTVhLTk5MzEtNjFlYjg3MjNlM2UxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDExMTA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZTBjZDcwYzQwNTMxMThlNDA3YzIyYWIyZDk2Zjg5NWNhZWIyNjY4Y2NjZDk4N2NlM2RiZDIzNDQ1M2ZlN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kqhE-XkHD93UVrofuj4ACgBnwGaIuD4PHBwFGie19R4)
> > So i am quite confused how can i convert my (image,masks,caption) to this format! I will really appreciate if you give me some informations about it, Thanks!!
> 
> Hello, I have original image (.png), corrseponding mask image (.png), and 5 captions every image, How can I convert them to these format as shown in this picture like xx.aesthetic_score, xx.caption, xx.height, xx.image, xx.original_key, xx.segmentation, xx.url, xx.width,

Hello，Is this problem solved?

**Comment by huangjie-nlp** [comment]
> Thanks for your novel work! **I would like to fine-tune your model on my custom dataset.** But in this repo there have no detail information about how to create my own BurshData set. I have downloaded few files from and when i have extracted i have seen something like this: ![brushdata](https://github.com/TencentARC/BrushNet/assets/61898803/ddcba30f-97bc-415a-9931-61eb8723e3e1)
> 
> So i am quite confused how can i convert my (image,masks,caption) to this format! I will really appreciate if you give me some informations about it, Thanks!!

Hello，Is this problem solved?
