### ISSUE TITLE
Flexible Control params not support ?

### ISSUE THREAD

**Issue by junqiangwu** [TencentARC/BrushNet#3]
### Model/Pipeline/Scheduler description

In section 4.3 of the paper, I saw that you mentioned blend operation, but I didn’t see them in the code?

### Open source status

- [x] The model implementation is available.
- [x] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by juxuan27** [comment]
Hi, @junqiangwu ! We have updated our code and readme. Please check the latest version!
