### ISSUE TITLE
Uncencored

### ISSUE THREAD

**Issue by barepixels** [TencentARC/BrushNet#30]
Humm I got "Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed."
 
How to remove the filter or can someone make a fork without the filter

**Comment by juxuan27** [comment]
Hi, @barepixels ! Please refer to [this](https://github.com/TencentARC/BrushNet/blob/ef14cadf3608560376f827e9e978b204ca44fd6f/README.md?plain=1#L264).
