### ISSUE TITLE
Can this network be trained with SDXL pretrained models?

### ISSUE THREAD

**Issue by xinli2008** [TencentARC/BrushNet#4]
Can this network be trained with SDXL pretrained models?

**Comment by juxuan27** [comment]
Hi, @xinli2008 ! Thanks for your focus. We are planning to do that. Please stay tuned!

**Comment by xinli2008** [comment]
Wow. It's exciting and looking forward to its release

**Comment by inferno46n2** [comment]
> Hi, @xinli2008 ! Thanks for your focus. We are planning to do that. Please stay tuned!

Very much looking forward to this! The 1.5 weights are fantastic!

**Comment by scarbain** [comment]
Hi @juxuan27, any idea on when BrushNet for SDXL might be released ? :)

**Comment by juxuan27** [comment]
Hi, @scarbain ! We will release the checkpoint in April. Please stay tuned!

**Comment by xinli2008** [comment]
will you also relase the inpaint pipeline and training code about brushnet-xl?

**Comment by juxuan27** [comment]
Yes, of course.

**Comment by jamarju** [comment]
Congrats on the great ideas exposed here! Was this ever released?

**Comment by juxuan27** [comment]
@jamarju Yes, an initial version of sdxl ckpt has been released, please refer to the readme. And we will release a better version soon.
