### ISSUE TITLE
Random brush model release ?

### ISSUE THREAD

**Issue by scarbain** [TencentARC/BrushNet#5]
### Model/Pipeline/Scheduler description

Hi, 

Thank you for releasing the 1.5 model for segmented inpainting. It's working pretty great but it's not working as well for masks that don't follow segmentations. Do you plan on releasing the random brush model as well ?

Thanks

### Open source status

- [ ] The model implementation is available.
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by juxuan27** [comment]
Hi, @scarbain ! We will release it soon. Please stay tuned!

**Comment by juxuan27** [comment]
Already released! Please check Google Drive.
