### ISSUE TITLE
About the Mask and Masked Image pair. Difference between training and test codes.

### ISSUE THREAD

**Issue by boom9807** [TencentARC/BrushNet#51]
This project helps me a lot. Thank you for your contribution!
I found some difference between training and test code about brushnet, which made me confused.
The details are as follows:
![8ae7fb36-6111-4618-9ded-68450139aa81](https://github.com/TencentARC/BrushNet/assets/42735246/daf9a9f4-5831-441b-913d-1d6cd35138ea)
The purpose of my training is to generate better background rather than foreground. As you can see, I set the probability of mask=1-mask to 0. According to the training code, the value of the foreground of the masked image is set to 0 and the background  is kept(is this right for generating background?). However, in the test code, the foreground is kept and the background  is set to 0 if the same binary mask is used.
Could you give an explanation for the difference between training and test codes? Many thanks!

**Comment by Kuanshen77** [comment]
+1
