### ISSUE TITLE
mask value problem

### ISSUE THREAD

**Issue by PlutoQyl** [TencentARC/BrushNet#7]
Code

I've noticed a detail that during training, the mask uses INTER_CUBIC and the latent dimension of the mask has continuous values between 0 and 1. However, during inference, it always uses discrete values of 0 and 1. Is there a problem with this?

**Comment by juxuan27** [comment]
Hi, @PlutoQyl ！Thank you for your focus. 
In fact, both in [inference](https://github.com/TencentARC/BrushNet/blob/60c165d59731a382f3bcba1f3656b06615a3a146/src/diffusers/pipelines/brushnet/pipeline_brushnet.py#L1123) and [training](https://github.com/TencentARC/BrushNet/blob/60c165d59731a382f3bcba1f3656b06615a3a146/examples/brushnet/train_brushnet.py#L756), we use interpolation to resize the mask. The interpolation may cause small errors, thus we use the blurred blending operation to provide an accurate mask.
