### ISSUE TITLE
Is it possible to guide inpainting using controlnet?

### ISSUE THREAD

**Issue by i-amgeek** [TencentARC/BrushNet#8]
### Model/Pipeline/Scheduler description

Hi, I am trying to inpaint a person in specific pose. Is it possible to use controlnet with this repo?

### Open source status

- [ ] The model implementation is available.
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by juxuan27** [comment]
Hi, @i-amgeek ! Thank you for your focus. I think it is theoretically sound to combine ControlNet and BrushNet together. But I haven't tried that personally. I may give it a try if I have the time. Moreover, we are welcome for any PR or discussion. Please tell us if you have tried that!

**Comment by loboere** [comment]
StableDiffusionBrushNetPipeline can load controlnet? or does it need to be modified?

**Comment by juxuan27** [comment]
I have retained the ControlNet functionality in this repo, but I am not sure whether it would work normally since I haven't tried that. If it works, please let me know! I will find time to try that maybe after a few days.

**Comment by jiechu520** [comment]
I have tried combining with controlnet，it works! need modified StableDiffusionBrushNetPipeline.

**Comment by juxuan27** [comment]
Hi, @jiechu520 ! Is that possible for you to pull your modification of StableDiffusionBrushNetPipeline to this repo and give us some examples? Thank you so much for your response!

**Comment by SlZeroth** [comment]
same!!! I want to use controlnet with brushnet. can you upload the code?

**Comment by SlZeroth** [comment]
@YoucanBaby can you share your code? I will test and fix the issue

**Comment by cs-mshah** [comment]
@jiechu520 can you show how to use controlnet with BrushNet. My goal is to finetune 2 controlnets on two different conditions (depth and normal) and also use the segmentation mask (going into the standard BrushNet). Can you please show an example on how this could be done.

**Comment by clarkkent0618** [comment]
> Hi, @i-amgeek ! Thank you for your focus. I think it is theoretically sound to combine ControlNet and BrushNet together. But I haven't tried that personally. I may give it a try if I have the time. Moreover, we are welcome for any PR or discussion. Please tell us if you have tried that!

I've tried it and it works well. I will PR later.

**Comment by cs-mshah** [comment]
@clarkkent0618 its amazing that ControlNet and BrushNet have worked well. I currently have depth maps with me along with segmentation maps for which I am thinking of training a ControlNet by using the depth maps and pass the segmentation maps to BrushNet. 
Can you just push code to your personal repository or raise a PR here on how to train a ControlNet along with BrushNet? I would really appreciate your effort since I have an urgent requirement for my project. 
Thanks!

**Comment by MasaiahHan** [comment]
Hi, I've implemented SDXLBrushnetControlnetPipeline and it works well either. Is there any way to open a PR?

**Comment by henbucuoshanghai** [comment]
is it very easy?

**Comment by MasaiahHan** [comment]
> 

quite easy, most of the work would be comparing controlnetxlpipeline and bruhsnetxlpipeline, and do the copy&paste job if you are familiar with the code.

**Comment by henbucuoshanghai** [comment]
I want to use controlnet with brushnet. can you upload the code?

**Comment by xduzhangjiayu** [comment]
Is there any open source code for this (BrushNet + ControlNet) in github?

**Comment by xduzhangjiayu** [comment]
> > I have tried combining with controlnet，it works! need modified StableDiffusionBrushNetPipeline.
> 
> Hi, can you show the input and output? I tried combining it with controlnet and got unsatisfactory output.

Hi, did you solve it ? I tried but also got wrong output
